# Variables
CXX = g++
CXXFLAGS = -std=c++17 -Wall
LIBS = -lsfml-graphics -lsfml-window -lsfml-system
TARGET = physics_sim

# Get all .cpp files in the directory
SRCS = $(wildcard *.cpp)

# Default rule
all: $(TARGET)

$(TARGET): $(SRCS)
	$(CXX) $(CXXFLAGS) $(SRCS) -o $(TARGET) $(LIBS)

# Clean rule to remove the executable
clean:
	rm -f $(TARGET)

# Rule to run the program
run: all
	./$(TARGET)