#include <SFML/Graphics.hpp>
#include <cmath>
#include <vector>
#include <string>
// this code is generated by ai , just to read it and try to solve why to moon is not turning around the earth 
// perfectly but it useless .
// ─── Gravitational constant (tuned for screen-scale simulation) ───────────────
constexpr float G = 6.674e-11f;  // real value — masses are scaled to compensate

// ─── Trail length ─────────────────────────────────────────────────────────────
constexpr std::size_t TRAIL_LEN = 400;

// ─── Body ─────────────────────────────────────────────────────────────────────
struct Body
{
    std::string       name;
    double            mass;        // kg (real-ish scaled values)
    float             radius;      // visual radius in pixels
    sf::Vector2<double> pos;       // metres → mapped to pixels via SCALE
    sf::Vector2<double> vel;       // m/s
    sf::Color         color;
    sf::Color         outlineColor;
    std::vector<sf::Vertex> trail;

    Body(std::string n, double m, float r,
         sf::Vector2<double> p, sf::Vector2<double> v,
         sf::Color c, sf::Color o)
        : name(n), mass(m), radius(r), pos(p), vel(v), color(c), outlineColor(o)
    { trail.reserve(TRAIL_LEN); }
};

// ─── Physics step (velocity-verlet style, single euler is fine at small dt) ──
void applyGravity(Body& a, Body& b, double dt)
{
    sf::Vector2<double> diff = b.pos - a.pos;
    double dist = std::sqrt(diff.x*diff.x + diff.y*diff.y);

    // Softening to avoid singularity if bodies get too close
    double softening = 1e8;
    double distSoft   = std::sqrt(dist*dist + softening*softening);

    double F   = G * a.mass * b.mass / (distSoft * distSoft);
    double Fx  = F * diff.x / distSoft;
    double Fy  = F * diff.y / distSoft;

    a.vel.x += (Fx / a.mass) * dt;
    a.vel.y += (Fy / a.mass) * dt;
    b.vel.x -= (Fx / b.mass) * dt;
    b.vel.y -= (Fy / b.mass) * dt;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
// Pixels per metre scale
constexpr double SCALE = 1.0 / 1.5e9;   // 1 pixel = 1.5e9 metres

sf::Vector2f toScreen(sf::Vector2<double> pos, sf::Vector2f centre)
{
    return centre + sf::Vector2f(
        static_cast<float>(pos.x * SCALE),
        static_cast<float>(pos.y * SCALE));
}

void updateTrail(Body& b, sf::Vector2f screenPos)
{
    if (b.trail.size() >= TRAIL_LEN)
        b.trail.erase(b.trail.begin());

    b.trail.push_back({ screenPos, b.color });

    for (std::size_t i = 0; i < b.trail.size(); ++i)
    {
        float frac = static_cast<float>(i) / static_cast<float>(b.trail.size());
        b.trail[i].color.a = static_cast<uint8_t>(frac * 180.f);
    }
}

sf::CircleShape makeCircle(float r, sf::Color fill, sf::Color outline)
{
    sf::CircleShape s(r);
    s.setOrigin({ r, r });
    s.setFillColor(fill);
    s.setOutlineThickness(1.5f);
    s.setOutlineColor(outline);
    return s;
}

// ─── Main ─────────────────────────────────────────────────────────────────────
int main()
{
    const unsigned W = 900, H = 900;
    sf::RenderWindow window(sf::VideoMode({ W, H }), "Solar System – Newtonian Gravity");
    window.setFramerateLimit(60);

    const sf::Vector2f centre(W / 2.f, H / 2.f);

    // ── Real-ish masses (scaled down uniformly so G*m products give screen-speed orbits)
    // We scale all masses by 1e-10 so velocities are screen-friendly
    constexpr double MS = 1e20;   // "Sun"   mass unit
    constexpr double ME = 3e17;   // "Earth" mass unit
    constexpr double MM = 3e15;   // "Moon"  mass unit

    // Earth orbit radius in our metre-space: 1 pixel = 1.5e9 m, Earth is ~200 px out
    constexpr double R_EARTH = 200.0 / SCALE;   // ~3e11 m
    constexpr double R_MOON  =  55.0 / SCALE;   // ~8.25e10 m

    // Circular orbit velocity: v = sqrt(G*M_parent / r)
    double vEarth = std::sqrt(G * MS / R_EARTH);
    double vMoon  = std::sqrt(G * ME / R_MOON);

    // Bodies — Sun at origin, Earth to the right, Moon above Earth
    std::vector<Body> bodies = {
        Body("Sun",   MS, 55.f,
             { 0.0, 0.0 }, { 0.0, 0.0 },
             { 255, 200,  50 }, { 255, 240, 100 }),

        Body("Earth", ME, 18.f,
             { R_EARTH, 0.0 }, { 0.0, vEarth },
             {  70, 130, 255 }, {  30,  80, 200 }),

        Body("Moon",  MM,  7.f,
             { R_EARTH, -R_MOON }, { vMoon, vEarth },   // vEarth added so Moon moves with Earth
             { 210, 210, 210 }, { 160, 160, 160 }),
    };

    // ── Starfield ──
    std::vector<sf::CircleShape> stars;
    srand(42);
    for (int i = 0; i < 180; ++i)
    {
        float r = (rand() % 2 == 0) ? 1.f : 0.5f;
        sf::CircleShape s(r);
        s.setOrigin({ r, r });
        s.setPosition({ static_cast<float>(rand() % W),
                         static_cast<float>(rand() % H) });
        uint8_t b = 140 + rand() % 116;
        s.setFillColor({ b, b, b, 200 });
        stars.push_back(s);
    }

    // ── Sun glow layers ──
    std::vector<sf::CircleShape> glow;
    for (int i = 4; i >= 1; --i)
    {
        float r = 55.f + i * 14.f;
        sf::CircleShape g(r);
        g.setOrigin({ r, r });
        g.setFillColor({ 255, 160, 0, static_cast<uint8_t>(18 * i) });
        glow.push_back(g);
    }

    // Physics timestep — large dt to speed up the simulation visually
    constexpr double dt = 3600.0 * 24.0;  // 1 day per frame
    constexpr int    STEPS_PER_FRAME = 24; // 24 days per rendered frame → fast but stable

    sf::Clock clock;

    while (window.isOpen())
    {
        while (const std::optional event = window.pollEvent())
        {
            if (event->is<sf::Event::Closed>())
                window.close();
            if (const auto* key = event->getIf<sf::Event::KeyPressed>())
                if (key->code == sf::Keyboard::Key::Escape)
                    window.close();
        }

        // ── Physics: run multiple small steps per frame ──
        for (int step = 0; step < STEPS_PER_FRAME; ++step)
        {
            // Apply gravity between every unique pair
            for (std::size_t i = 0; i < bodies.size(); ++i)
                for (std::size_t j = i + 1; j < bodies.size(); ++j)
                    applyGravity(bodies[i], bodies[j], dt);

            // Integrate positions
            for (auto& b : bodies)
            {
                b.pos.x += b.vel.x * dt;
                b.pos.y += b.vel.y * dt;
            }
        }

        // ── Sun stays at screen centre (we track relative positions) ──
        // Shift everything so the Sun is always centred
        sf::Vector2<double> sunPos = bodies[0].pos;
        for (auto& b : bodies)
            b.pos -= sunPos;
        // Also correct velocity (subtract Sun's drift — keeps simulation in Sun's frame)
        sf::Vector2<double> sunVel = bodies[0].vel;
        for (auto& b : bodies)
            b.vel -= sunVel;

        // ── Update screen positions and trails ──
        for (auto& b : bodies)
        {
            sf::Vector2f sp = toScreen(b.pos, centre);
            updateTrail(b, sp);
        }

        // ── Draw ──
        window.clear({ 5, 5, 18 });

        for (auto& s : stars) window.draw(s);

        // Trails
        for (auto& b : bodies)
            if (b.trail.size() > 1)
                window.draw(b.trail.data(), b.trail.size(), sf::PrimitiveType::LineStrip);

        // Glow + bodies
        sf::Vector2f sunScreen = toScreen(bodies[0].pos, centre);
        for (auto& g : glow) { g.setPosition(sunScreen); window.draw(g); }

        for (auto& b : bodies)
        {
            sf::Vector2f sp = toScreen(b.pos, centre);
            auto shape = makeCircle(b.radius, b.color, b.outlineColor);
            shape.setPosition(sp);
            window.draw(shape);
        }

        window.display();
    }

    return 0;
}